apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-project
  namespace: argocd
  labels:
    app: dev
spec:
  description: Argo CD project for applications, controlling repos and namespaces
  sourceRepos:
    - https://github.com/pragmatic-antithesis/inception-of-things-maalexan.git
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
