# Vagrantfile
# -*- mode: ruby -*-
# vi: set ft=ruby :

def vm_specs(vbox, hostname)
  vbox.gui = false
  vbox.name = hostname
  vbox.memory = 2048
  vbox.cpus = 1
end

Vagrant.configure('2') do |config|
  config.vm.box = 'generic-x64/alpine319'
  config.vm.box_version = '4.3.12'

  config.vm.define 'inwagnerS' do |server|
    server.vm.hostname = 'inwagnerS'
    server.vm.network 'private_network', ip: '192.168.56.110'

    server.vm.provider 'virtualbox' do |vbox|
      vm_specs(vbox, 'inwagnerS')
    end
    server.vm.provision 'file', source: 'confs/', destination: '/home/vagrant/'
    server.vm.provision 'shell', path: './scripts/setup_k3s.sh', env: { 'NODE_IP' => '192.168.56.110' }
  end
end
