# Vagrantfile
# -*- mode: ruby -*-
# vi: set ft=ruby :

SERVER = 'inwagnerS'.freeze
PROVIDER = 'virtualbox'.freeze
PROVISION = 'shell'.freeze
SCRIPT = './scripts/setup_k3s.sh'.freeze
NETWORK = 'private_network'.freeze
IPS = {
  SERVER => '192.168.56.110'
}.freeze
BOX = 'generic-x64/alpine319'.freeze
BOX_VERSION = '4.3.12'.freeze

def vm_specs(vbox, hostname)
  vbox.gui = false
  vbox.name = hostname
  vbox.memory = 1024
  vbox.cpus = 1
end

Vagrant.configure('2') do |config|
  config.vm.box = BOX
  config.vm.box_version = BOX_VERSION

  config.vm.define SERVER do |server|
    server.vm.hostname = SERVER
    server.vm.network NETWORK, ip: IPS[SERVER]

    server.vm.provider PROVIDER do |vbox|
      vm_specs(vbox, SERVER)
    end
    server.vm.provision 'file',
      source: "./confs/",
      destination: "/home/vagrant/"

    server.vm.provision PROVISION,
      path: SCRIPT,
      env: {
        'NODE_IP' => IPS[SERVER]
      }
  end

end
